### PR TITLE
Time-based simulation

### PR DESCRIPTION
**Pull request by a-mathis**

### CODE REVIEW

**Comment by KlewinS** [comment]
Something seems to be still strange with the timebins. If I run a short simulation with 2 events (setting) and reading the digits afterwards from the file, then the events 0 and 1 are empty, events 2 and 3 contain both timebins 38 to 85, event 4 86 to 593 and event 5 again empty. I don't worry about the empty events, but problematic is, that event 2/3 contain the same timebins.

**Comment by a-mathis** [comment]
Thanks for the observation. There is clearly something going wrong with FairRootManager::Fill() which we use to fill the TClonesArray. I will look into this and provide a fix asap once the rebase to O2/dev is complete.

**Comment by KlewinS** [comment]
no Problem, I will just filter them out for the moment

**Comment by a-mathis** [comment]
The bug is now fixed in https://github.com/wiechula/AliceO2/pull/15. Please note however, that running 10 events now results in 11 events written to disk, out of which the first is empty. There is no straight-forward solution for this at the moment, as all this is handled within FairRoot.

**Pull request merged**
